### PR TITLE
new bot commands setslacktag and showslackrealnames

### PR DESCRIPTION
**Pull request by errror**
avoids two api queries per message sent from slack!
also rewrote get_channel_users function to use already cached channel
and user data instead of refetching all of it again

### CODE REVIEW

**Comment by errror** [comment]
while implementing setslacktag and showslackrealnames bot command, I discovered some caching issues, that lead to extensive Slack API usage.

The two new commands are the result of user complains, that did not like the previous changes by other contributors. They allow to configure if messages from slack are enhanced with the Slack's team name (might be long, disturbing and/or obvious) and to switch back to the old behaviour to display the user's username instead of realname.

**Comment by thannemann** [comment]
Thank you for the config commands I was doing it by hand each time I update

**Comment by pleasantone** [comment]
Merged, not super happy about adding more prints, but wtf.

**Comment by errror** [comment]
@pleasantone which more prints?

**Comment by cd334** [comment]
I tried out and the new command working very well! THX!

**Pull request merged**
