### PR TITLE
Allow logging to be configured by the user instead of hard coded

### PR DESCRIPTION
**Pull request by pleasantone**
Use logging's dictConfig to configure logging, mimicking prior behavior, unless a "logging" component
exists in our configuration file.

"Bootstrap in" the configuration file before we even begin to instantiate class, just for a single read-in
and then throw it away.  If an error/debug message happens before we manage to load the config,
logging() will instantiate a "no-brainer" configuration and at least get the message out to stderr.
Once our more sophisticated configuration is loaded, all will be as normal.

I put the logging dict in the code, instead of in the sample config.json to avoid migration issues
and to support the existing command line arguments (--debug and --log).

Here is an example of how this can be used (config.json snippet), where I have taken the
default configuration, changed hangupsbot.log to rotate at 1mb (keep 3 old ones), and
also send output to syslog:

```
  "logging": {
    "version": 1,
    "disable_existing_loggers": false,
    "formatters": {
      "default": {
        "format": "%(asctime)s %(levelname)s %(name)s: %(message)s",
        "datefmt": "%Y-%m-%d %H:%M:%S"
      },
      "console": {
        "format": "%(asctime)s %(levelname)s %(name)s: %(message)s",
        "datefmt": "%H:%M:%S"
      },
      "syslog": {
        "format": "hangupsbot[%(process)d]: %(levelname)s %(name)s: %(message)s"
      }
    },
    "handlers": {
      "console": {
        "class": "logging.StreamHandler",
        "stream": "ext://sys.stdout",
        "level": "INFO",
        "formatter": "console"
      },
      "file": {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": "/home/discobot/.local/share/hangupsbot/hangupsbot.log",
        "maxBytes": 1048576,
        "backupCount": 3,
        "level": "INFO",
        "formatter": "default"
      },
      "syslog": {
        "class": "logging.handlers.SysLogHandler",
        "level": "DEBUG",
        "address": "/dev/log",
        "formatter": "syslog"
      }
    },
    "loggers": {
      "": {
        "level": "INFO",
        "handlers": [ "file", "console", "syslog" ]
      },
      "hangups": { "level": "ERROR" },
      "requests": { "level": "INFO" },
      "hangups.conversation": { "level": "ERROR" },
      "asyncio": { "level": "WARNING" }
    }
  },
```

### CODE REVIEW

**Comment by endofline** [comment]
This crashes on merge:
```
Traceback (most recent call last):
  File "/root/projects/nihalbot/hangupsbot/hangupsbot.py", line 1043, in <module>
  File "/root/projects/nihalbot/hangupsbot/hangupsbot.py", line 1033, in main
  File "/root/projects/nihalbot/hangupsbot/hangupsbot.py", line 986, in configure_logging
    logging.getLogger('asyncio').setLevel(logging.WARNING)
  File "/usr/lib/python3.4/logging/config.py", line 789, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.4/logging/config.py", line 489, in configure
    raise ValueError("dictionary doesn't specify a version")
ValueError: dictionary doesn't specify a version
```

I will do further testing to identify the issue

**Comment by endofline** [comment]
Oh, we have a conflicting `config.json` key `logging` - the [Logger to Chat Message](https://github.com/hangoutsbot/hangoutsbot/wiki/Logger-to-Chat-Message) was added recently - it has the same key

**Comment by pleasantone** [comment]
Aha! OK, I should rename mine… suggestions?

**Comment by endofline** [comment]
`logging.system` perhaps? ;P then in the future, I can migrate the too-general `logging` key to something more specific without conflicts

**Comment by endofline** [comment]
Added to #300, Framework 2.7 preliminary documentation updated with [new section](https://github.com/hangoutsbot/hangoutsbot/wiki/Framework-2.7#customisable-python-logging)

**Pull request merged**
