### PR TITLE
Update lookup to Googles sheet api v4

### PR DESCRIPTION
**Pull request by MTRNord**
This pull changes the lookup code to use the API instead of parsing HTML

## New Features
- Lets you define any sheet
- Removes the 100 lines limit that is mentioned in the wiki
- Doesn't need to publish the files

## Changes
- Needs you to get a serviceaccount creds.json (wiki will get an explanation)
- Quota limit of 40,000 queries per day
- You need to share the sheet with the Email of the Service Account (Google will Send a Email that the Server wasn't found. But that can be ignored) 

## TODO

- [X] Update Basic function
- [x] Readd Data output
- [x] Pretty Print Output
- [x] Readd `_("foo")` syntax 
- [x] Add backwards compatibility (done but maybe needs to be discussed)
- [x] Add needed libs to the requirements.txt
- [x] Update Wiki (Draft is located at: https://gist.github.com/MTRNord/4ff0b22a779fbfeb0f57a72ca6acc5f7  )

### CODE REVIEW

**Comment by nylonee** [comment]
I'm mobile right now so just a quick note or two... When I get on a computer later I'll add more thoughts.

 * Please maintain backward compatibility so that users who have been using the lookup plugin in the past can continue to do so without having to reconfigure anything
 * Retain the `_("foo")` formatting so that we don't break locales
 * This is your second WIP PR that you've submitted, and it sits in the PR list until you're done with your work (which might take months). It might be better to submit a PR when you're closer to completion and ready for a proper code review.

**Comment by MTRNord** [comment]
Ok I have both pr's nearly finished. I will submit them on the weekend. Sorry for that. backward compatibility will be added.

**Comment by MTRNord** [comment]
@nylonee do you have any other things that do bother you in terms of functions? As backward compatibily I now parse the old url and make it to the new one. Is that backward compatible enough or should I make a big if else around it which contains the full old code? (ps the requirements.txt will I fill when everything is ok to have no conflicts with it yet.)

**Comment by MTRNord** [comment]
Also as I am first time editing the wiki: Whats the best way to mention that my setup is only required with the version that than would/will be in staging? Because my Pull pretty much changes the hole Plugin setup

**Comment by endofline** [comment]
No offense intended but "changing the whole plugin setup" raises a red flag
to me...

Some questions:
* What happens with bots that may have old config keys? Will errors be
thrown?
* How much work is required to migrate? Is an automatic migration script
viable?

As this is a WIP, so no wiki modifications to existing pages until the PR
is merged to staging. However you can create a separate preliminary wiki
doc page that you can link through this issue for review. We also will not
merge the code because it's in an incomplete state, and will rely entirely
on what you communicate via this issue. Therefore, please elaborate here
what are the basic requirements and possible caveats so that we can discuss
and resolve prior.

**Comment by MTRNord** [comment]
@endofline hi so the main change is that using The api requires you to create a Service Account. I will make a not listed wiki Page for Review later this day. 

In terms of backwards compatibility it currently converts only The URL to the New one . 
I could readd The old Code and Check If it is a old url Or a new one. Than I would Tell The admins on the init of the plugin that They use The old Features and there is a new way of using The plugin. (I would Tell them on plugin load as i want to prevent to do spam)

**Comment by MTRNord** [comment]
In terms of migration automation there is propablly needed to get The admins and create a Serviceaccount i will test If the bot cookie is compatibile with The sheets api. If it is the admin will have nothing to do. If it is not the admin has to click trough a Web interface to create The serviceaccount. Also the api requires that you share The sheet with this Serviceaccount. (only required once)

**Comment by MTRNord** [comment]
I tried to get around using a serviceaccount by using the refresh token but sadly that gives:

`RequestError: (401, '401: b\'<HTML>\\n<HEAD>\\n<TITLE>Token invalid - AuthSub token has wrong scope</TITLE>\\n</HEAD>\\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\\n<H1>Token invalid - AuthSub token has wrong scope</H1>\\n<H2>Error 401</H2>\\n</BODY>\\n</HTML>\\n\'')`

so with using api serviceaccounts are required as it otherwise does not have the needed scopes.

Code using the refresh token of the bot would have been: https://gist.github.com/MTRNord/081320c0173132d31d231714a6358486

**Comment by jumoog** [comment]
maybe you mention the url to the wiki if the old config is detected?

**Comment by thannemann** [comment]
What do you mean a service account? can the bot not use it's own google account to get the data if you share it with the bot?

**Comment by MTRNord** [comment]
@thannemann no it requires a "serviceaccount" which is a special api account by google. I tried to use the google bot account but that didn't work as google sheets needs other permissions than the bot does.
A serviceaccount is basicly a account which makes a server to server connection with google and has it's own mail address. You can read more how to create one here: http://gspread.readthedocs.io/en/latest/oauth2.html

(My Wiki Page is partially ready.)

**Comment by thannemann** [comment]
Thanks for the link to the oath2 information it was not a service account as I was thinking

**Comment by MTRNord** [comment]
@jumoog if the rest in here agrees with it I will add a admin message which runs on plugin load which tells the admins if they got a "legacy"(/old) URL in the config to take a look at the wiki and tells a line or so about what changed or how to update. Or do you think "spamming" on every run is better (I personally don't think that would be good on every run)

**Comment by MTRNord** [comment]
The Wiki Page is able to be reviewed on https://gist.github.com/MTRNord/4ff0b22a779fbfeb0f57a72ca6acc5f7 

The example and explanations should be updated correctly. The example is the same sheet as a copy to be able to share it for everyone that has the link (but not yet tested that. working on it currently).

PS: I decided against using Images for the Serviceaccount as I don't want to overfill the Wikipage

**Comment by MTRNord** [comment]
So the example currently is not able to work due to the used lib. their upstream pull can you find here: https://github.com/burnash/gspread/pull/345

I will mention it there that they are allowed to share it to their bot for testing and will mention the above PR. There is a fork which supports it but I don't want to use it because I want a well updated lib instead of a fork (I think you can understand that)

**Comment by MTRNord** [comment]
For understanding the last commit: I decided to make it to a dir plugin to keep it a 100% compatible and to let the admins have the option to switch.

**Comment by MTRNord** [comment]
If you are ok with the dir structure and the Wiki Draft (linked in description of pr) it should be ready to merge. If any other things are missing than I of course will fix them

**Comment by nylonee** [comment]
Am going through this code now. 
In the meantime, just wanted to bring up the point that publishing a sheet is not a security concern. “Publishing a doc does not affect its visibility option". See [source](https://productforums.google.com/forum/#!topic/docs/ngSKdFlBNUk)

I admit the word 'publishing' is a bit misleading here, but the only reason we ask for a published sheet is because it is then formatted nicely in an HTML format that the plugin can read.

**Comment by MTRNord** [comment]
Ok :) yes "publishing" is a little missleading.

**Comment by endofline** [comment]
In the interest of time and focus, I will defer any review, testing and merge of this PR until after a v3 migration. Feel free to add to it though, or publish more comprehensive documentation as markup inside the pr body.

**Comment by MTRNord** [comment]
Ok I will wait and edit the pr body :)

**Pull request closed without merging**
