### PR TITLE
Telesync, slackRTM, join_message

### PR DESCRIPTION
**Pull request by JosephBlock**
Now uses memory.json for storage
Message can be changed via /bot join_message <message>
Also can be enabled/disabled via /bot join_message_enabled <true/false>

### CODE REVIEW

**Comment by JosephBlock** [comment]
Telesync fix for converting to supergroup

SlackRTM sync one slack channel to many hangouts
    `hangout <> Slack <> hangout`
What will not work
    `Slack <> hangout <> Slack`
Sending to a second Slack currently not possible as the thread only knows its own Slack team

Sorry that the commits were included all on this pull request.

**Comment by azack** [comment]
@JosephBlock this has merge conflicts

**Comment by nylonee** [comment]
@JosephBlock Can you please create the pull requests for each issue separately, as such this also has merge conflicts at the moment which should be resolved.

**Comment by nylonee** [comment]
@JosephBlock Is there still interest in getting this code merged? If so, submit the PR for each issue separately.

Closing this PR.

**Pull request closed without merging**
