### PR TITLE
slack-legacy: Add a way to sync per room

### PR DESCRIPTION
**Pull request by jumoog**
if you setup multi slack hooks you can sync every room seperate
Array (channel and synced_conversations) must have same lenght and order. 
Based  on current synced_conversations the right slack channel will be picked.

example:

   #development <-> UgwYjR0Q6ygVn7evyWR4AaABAQ
   #general <-> UgzBlVbTLVqV7PHWvPt4AaABAQ

current behavior:

   #development <- UgwYjR0Q6ygVn7evyWR4AaABAQ
    ----------------- ↘
   #general <-> UgzBlVbTLVqV7PHWvPt4AaABAQ

Config:
  "slack": [
    {
      ...
      "channel": ["#development", "#general"],
      ...
      "synced_conversations": [
      "UgwYjR0Q6ygVn7evyWR4AaABAQ",
      "UgzBlVbTLVqV7PHWvPt4AaABAQ"
      ],
      "multi_hooks": true
    }
  ],

### CODE REVIEW

**Comment by jumoog** [comment]
it's configurable and false per default

**Comment by nylonee** [comment]
I don't think I quite understand what this does, can you explain it a bit more?

From what I understand, it allows you to map a sync to multiple channels/rooms from the same config without having to make new configs for every channel you want to sync.

If that's the case, I'd prefer that we instead create a migration script to move current users of the slack config to using array-defined channels, so that multi-hooks are automatically assumed if the user's put in more than one channel in the array.

**Comment by jumoog** [comment]
yes you sync multiple channels/rooms from the same config.. saves alot config work

**Comment by nylonee** [comment]
I suppose it's about time I looked at this commit xD It's for a legacy plugin, so it's not critical, but it'd be good to clear up the old PR's.

I won't create migration scripts for this, but instead allow the plugin to continue as normal if this is not set. Moving this to a `jumoog-master` branch for the time being.

**Pull request closed without merging**
