### PR TITLE
thread management + chatbridge

### PR DESCRIPTION
**Pull request by endofline**
* standardised thread management to `thread_manager` module
* adapted proposed submodule Chat_Framework (https://github.com/hangoutsbot/chat_framework) into framework (re: @nylonee, re: #201)

### CODE REVIEW

**Comment by nylonee** [comment]
Would the reprocessor plugin not be able to work from within the framework? If so, what are our options (or is the process now redundant)

**Comment by endofline** [comment]
Reprocessor is exposed via `bot.call_shared("reprocessor.attach_reprocessor")` (example: https://github.com/hangoutsbot/hangoutsbot/blob/staging/hangupsbot/plugins/slack.py#L199) - doesn't really have any direct relationship with this framework change, unless whatever bridge requires it - then it can be used as normal.

**Comment by nylonee** [comment]
I vote we keep this open until we find that it's actually coming in useful in developing new chat bridges.

**Comment by endofline** [comment]
I'm promoting this part of the framework, but will probably rename `chatbridge` to `webchatbridge` as a more specific and informative term

**Comment by endofline** [comment]
All changes accounted for in #217 PR description

**Pull request merged**
