### PR TITLE
slack-legacy: respect OTR privacy

### PR DESCRIPTION
**Pull request by jumoog**
if history is off respect that and don't for forward these messages to Slack.

### CODE REVIEW

**Comment by pleasantone** [comment]
This needs to be configurable, with the default being current behavior.

Slack allows us to clean up history after the fact, hangouts doesn't, so Slack is "more secure" in the default case.

**Comment by jumoog** [comment]
true but if you add new people to hangout they cant read what was writen when history was off

**Comment by pleasantone** [comment]
I suspect I understand your use case, the point is that in that scenario, we have people in the slack channel who need to participate in the conversation when history is off.

**Comment by jumoog** [comment]
yes i switch history off when we talk about secrect stuff but maybe we can add self destroying messages (slack bot delete it after XY seconds)

**Comment by pleasantone** [comment]
If you make it configurable, with the default being the current behavior, I'll be happy to merge it, otherwise it will go wontfix.  Sorry.

**Comment by jumoog** [comment]
it's configurable and false per default

**Comment by pleasantone** [comment]
Merged by hand into staging (not master). Will close when staging is next merged into master.

**Pull request merged**
