### PR TITLE
Add Spotify plugin for adding music to chat playlists.

### PR DESCRIPTION
**Pull request by linguinee**
Short screencast: http://i.imgur.com/VtS6IDb.gif

### CODE REVIEW

**Comment by nylonee** [comment]
This looks awesome. Can you add the config and instructions to the wiki?

**Comment by linguinee** [comment]
Thanks! Created a [Spotify Plugin](https://github.com/hangoutsbot/hangoutsbot/wiki/Spotify-Plugin) page and added it to the [Plugin List](https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-List) as well.

**Comment by linguinee** [comment]
Ping?

**Comment by sabinico** [comment]
@linguinee Can you make a more explained setup guide? I'm trying to get the Spotify token but I got an error. What I need to set into the redirect_uri, these uri needs to run a php script for authentification? I'm stuck in this part.

**Comment by linguinee** [comment]
I updated [the page](https://github.com/hangoutsbot/hangoutsbot/wiki/Spotify-Plugin) with more information – the redirect URI can be set to anything, it just needs to be exactly the same as what you enter into the redirect URI whitelist in your [registered application](https://developer.spotify.com/my-applications/#!/applications).

**Pull request merged**
