### PR TITLE
Update simplytranslate

### PR DESCRIPTION
**Pull request by flagmaggot**
Fix will repair the 503 error after running the translation command a few times. Only requirement is to install TextBlob:
pip install -U textblob

### CODE REVIEW

**Comment by nylonee** [comment]
Nice! Can you put the textblob requirement into requirements.txt?

**Comment by flagmaggot** [comment]
Done!

**Comment by nylonee** [comment]
For future reference, if you had updated this branch in your original fork with the requirements.txt commit, it would have automatically updated this PR with the new files added.

No worries, I'll merge them all =)

**Comment by flagmaggot** [comment]
Ah thanks. It's been a while since I've used github.

**Pull request merged**
