### PR TITLE
Validating image links in a seperate file which is called from autoreply.py humor_hangoutcalls.py and image_links.py

### PR DESCRIPTION
**Pull request by thannemann**
New pull request to resolve issues brought up in #569.  Moved all Image validation code to the supporting _validate_image_links.py file and call it from each of the three plugins.

### CODE REVIEW

**Comment by endofline** [comment]
why not use `register_shared`/`call_shared` syntax for validation plugin and dependents? docs: https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-Authoring-(2.4-and-above)#sharing-plugin-functionality

**Comment by endofline** [comment]
also: line breaks at the end of your files (or lack thereof), you might want to adjust your IDE for that

**Comment by thannemann** [comment]
Thanks for the comments I can look further at this as I am learning as I do this.  I will change my IDE as I have not really been using a great one. I commented on #753 but should we make these changes breaking backwards compatibility of existing bots by moving the files / changing the config.json syntax?

**Comment by thannemann** [comment]
so keeping this separate from the discussion in #753.... I guess the current discussion here is should we use the register_shared/call_shared as that means another plugin to add in the config (breaking changes for existing bots using the image_load function), if we are not moving the files the call to the include file is not as fragile.  I am of the mindset to keep the backwards functionality, and not break old bots.

**Comment by endofline** [comment]
I have done a full test of this PR and found broken or incomplete functionality. To create a working version from this PR, I have pulled  and created a new branch: https://github.com/hangoutsbot/hangoutsbot/tree/image_folder and committed some extra work on top of the changes here:
* folder plugin `image` + moving all image-centric plugins into the folder (3295d3b100bee0e5f22573aaf07dac22204bb4fe)
  * implement the `register_shared` functionality (35a2c0eb709abf393989713a0296650b818ca3f5)
* plugin image_links
  * added image validation fallback code for devs who don't want or cannot load the image plugin in a timely manner (35a2c0eb709abf393989713a0296650b818ca3f5)
* plugin autoreply
  * added image validation fallback code for devs who don't want or cannot load the image plugin in a timely manner (35a2c0eb709abf393989713a0296650b818ca3f5)
  * removed `autoreplies_list_global` - this feature is incomplete and breaks plugin startup! (57e4a4ca8a4d702bc3b54ed9cfd9b5de8f84b922)
* plugin humor_hangoutcalls
  * reverted all proposed changes as the proposed mechanism is unworkable (ab2eaf6a17cf1c4ffc0078484d92fba08f196c4c)
* code cleanup - **please check your IDE** (54280afeac20b775505d2270a3947770bf65fd23)
  * converted windows linebreaks to unix linebreaks
  * removed tabs in the code
  * remove empty "blank" lines consisting of white space
* reduced verbosity of logging when shared functionality is correctly used (dd7379c6b6c1d59a45c55a7807c7995258ca4124)

it is **highly recommended** that you continue development by freshly checking out the `image_folder` branch OR pull/merge the branch into this PR. the `image_folder` branch contains the latest `staging` + this PR #749 + changes listed above

**Comment by endofline** [comment]
I note that this PR is directly from your own staging branch. You should consider creating a new feature branch from a clean staging so that you can work on features independently of each other. Since I have already created the image_folder branch, you can pull this into your feature branch for further work. In the meantime, I'm closing this PR as it's not in a useable state - please see my previous comment.

**Comment by PrinterElf** [comment]
WTF have you done to autoreply?!?
It works perfectly well when you haven't deleted lines 42-46 from the commit!!!
https://github.com/PrinterElf/hangoutsbot/blob/a1f29ef001e709fad2996bf7b18a8968ad796f2c/hangupsbot/plugins/autoreply.py

If you can't even take a cut of code correctly, WTF are you doing editing other people's work?!?

**Comment by thannemann** [comment]
@PrinterElf I assume you are talking about my butchery of the code, I apologize I was trying to separate my original PR #569 from yours, #731 so you could continue developing it, as I thought your PR mention something was not working with it (https://github.com/hangoutsbot/hangoutsbot/pull/731#issuecomment-280588684).  It was not intentional editing of your code but I appreciate you correcting it so I don't fuck it up again.....

**Comment by endofline** [comment]
for future reference @thannemann:
* you need to branch your forked staging when working on a feature/fix:
  * maintaining multiple separate feature/fix branches with lots of small commits with meaningful log messages are a **necessity** in git - it is what makes git powerful, and also what makes it occasionally painful but bearable, rather than doing omnibus all-in-one commits that complicate code review. 
```
# anywhere inside your local git working copy
git checkout staging # checkout latest copy of staging on your repo
git checkout -b feature1 # creates new branch and switches to it
```
* you can figure out which branch you're in at all times with:
```
git status
```
* if you're working with multiple sources, add remote origins and pull/merge from them often so that changes made in another branch (by other contributors) are reflected properly (i missed the [original source](https://github.com/PrinterElf/hangoutsbot/blob/a1f29ef001e709fad2996bf7b18a8968ad796f2c/hangupsbot/plugins/autoreply.py#L46) by printerelf because i couldn't `git blame` the source tree prior to 57e4a4ca8a4d702bc3b54ed9cfd9b5de8f84b922).
  * you only have to add the remote once, then you can pull/merge at any time
  * there are many ways to do pulling and merging, this is just one-way to do it:
```
# add printerelf's repo and merge the printerelf/patch-4
# note: "printerelfrepo" is any label you want to use to recognise the remote origin
git remote add printerelfrepo git@github.com:PrinterElf/hangoutsbot.git
git pull printerelfrepo patch-4

# add the hangoutsbot "master" repo and merge staging
# note: "rootrepo" is any label you want to use to recognise the remote origin
git remote add rootrepo git@github.com:hangoutsbot/hangoutsbot.git
git pull rootrepo staging
```
* as much as possible, **work entirely within your own repo**, and then issue a cross-repo pull request when the code is **completed (or near-complete) and tested**. we **discourage *Work-In-Progress* PR**s as it adds to the noise for framework devs
  * if you want to FYI us on a new feature you're working on, you can use the Issue Tracker to outline your plans instead, and link to your working branch in the issue body
  * **testing is especially important** since we don't have automated runners. as a rule of the thumb (for this project), do not push to a remote repo until you have at least done some cursory testing and no warnings/errors are thrown during bot initialisation

hope you don't read me as dissing you, just thought to post this as a guideline to reduce issues in the future. additionally some of these items will be a good addition to #650

**Comment by thannemann** [comment]
@endofline I have taken everything as constructive criticism as this is a learning experience for me.

**Comment by PrinterElf** [comment]
@thannemann Apologies overdue due for the rant - I really should not look at git after a more than frustrating day at work! Tbh I'm surprised I haven't managed to do similar myself so far, and I have a feeling that before we get to v3 things are going to get even more complex!

**Comment by thannemann** [comment]
@PrinterElf thanks and I do understand your frustration with how I screwed it up.

**Pull request closed without merging**
