### PR TITLE
Add support for Cross-Origin Resource Sharing

### PR DESCRIPTION
**Pull request by fkloft**
This adds support for [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) to allow the API to be used from web pages across domains. By removing `False and` and adding a list of valid origins in line 91, this may be restricted to certain hosts. This could maybe converted to a config setting?

### CODE REVIEW

**Comment by gurumadmat** [comment]
It's always best to have it work with config settings.

**Comment by pleasantone** [comment]
LMK when you have it working with a config option, felix.

**Comment by pleasantone** [comment]
@fkloft you going to update to handle config.json?  Also, please target staging, not master -- https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

**Comment by fkloft** [comment]
Added configuration option `api_origins`; may either be `"*"` or a list of valid origins (c.f. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)). CORS disabled by default for security reasons.

**Comment by fkloft** [comment]
It is. Currently (without this PR), all non-primitive requests are rejected because the server doesn't react to the browser's preflight request. If `api_origins` isn't set, the method will return `HTTPForbidden`, which causes the browser to reject the request as well.

**Pull request merged**
