### PR TITLE
Add a Debian (Raspbian) init.d script for hangouts bot.

### PR DESCRIPTION
**Pull request by DanielCasner**
I don't know if startup scripts are something you want to include in the repository but in case it is useful, here is one I have configured (and documented) for the Raspberry Pi).

For greater flexibility with tolerance to disconnects, I added a maximum retries command line argument.

### CODE REVIEW

**Comment by nylonee** [comment]
We can add the startup script into the examples folder, it looks pretty well documented.

Could you talk more about what you changed within the core hangoutsbot.py file? It looks like a useful change, but I'm more interested in how it affects current users and future users. Will users have to modify something to get this PR working?

**Comment by pleasantone** [comment]
If we're going to do this, I also have a complimentary startup script for systemd (sigh) based systems.
I'll branch/upload for your pleasure.

@DanielCasner - I'm not sure why your script is labeled as pi specific -- raspbian is debian and from a quick perusal, it should work with ANY LSB compatible distribution.

**Comment by DanielCasner** [comment]
@nylonee All I changed in the hangoutsbot.py file is adding a command line option to specify *max_retries* so the script can be called with a different option than 5 when run as a daemon. This actually makes the instantiation of the `HangupsBot` class more consistent as all the other options were already set from the command line. This should not change the behavior for existing users at all because *retries* is an optional argument and if it is omitted the behavior will be identical to before this change.

@pleasantone I was originally going to call this a general Debian init script and it is very close to being so but there are some assumptions built into the script (`HOMEDIR` and python3 binary path) which are specific to Raspberry Pi. It would be trivial for anyone using it to change it to work with a different system. I'll update the documentation in the script to call this out.

Thank you.

**Comment by DanielCasner** [comment]
If there is a different place than the root of the repository where example init scripts should be placed, please advise.

**Comment by pleasantone** [comment]
Examples/

**Comment by DanielCasner** [comment]
@pleasantone Thanks, now that there is an Examples folder.
I've rebased off the latest master and squashed back down to one commit so the history is pretty if you decide to merge this.

Thank you.

**Comment by DanielCasner** [comment]
Are there any outstanding issues with this PR that I still need to resolve?

**Comment by nylonee** [comment]
File looks good, I'll test and prepare for merge

**Comment by thecanfield** [comment]
I am sure this is not the correct place to ask setup questions. However, I am not sure where to ask. Can someone please point me in the right direction? I have setup the bot and it works, I have configured this file with what I believe are the correct settings. When I run 'sudo /etc/init.d/hangoutsbot start' i get '[ok] Starting hangoutsbot (via systemctl): hangoutsbot.service.' as if everything is fine but, the bot is not functioning. I have looked for '/var/log/hangoutsbot.log' to see what the error may be but no log exists. Thank you again for any help.

**Pull request merged**
