### PR TITLE
remove unicode symbols from HO sender name resp. tag when used as sender in synced slack message

### PR DESCRIPTION
**Pull request by errror**
Slack does not like unicode symbols in sender name of synced messages, but as the hotag gets part of the sender name and those cracy Ingress guys like to add flags and other stuff in the HO name, we have to filter them out.

### CODE REVIEW

**Comment by JosephBlock** [comment]
What does it error out on?  Which characters?

**Comment by JosephBlock** [comment]
@errror I just checked my slack. And it handles utf-8 fine for the names.  If your seeing errors in the logs, I had to add .decode("utf-8") to strings which fixed the errors

**Comment by pleasantone** [comment]
Just a quick comment, we don't need the utf-8... decode() defaults to utf-8 in python3

**Comment by errror** [comment]
Hi @pleasantone ,

the only `decode('utf-8')` call I can find is in the api_call wrapper, which I got by a merge from the hangoutsbot repo. See here https://github.com/hangoutsbot/hangoutsbot/issues/526

**Comment by nylonee** [comment]
Is this still an issue? Does this PR need to be merged?

**Comment by pleasantone** [comment]
@errror is this an issue, or can we close it without merging?

**Comment by pleasantone** [comment]
Problem unreproducible.

**Pull request closed without merging**
