### PR TITLE
[v3] SlackRTM rewrite

### PR DESCRIPTION
**Pull request by OllieTerrance**
This is a Slack chatbridge plugin, Rewritten To Mastery.  😏  (It also happens to use the RTM APIs.)

As the name suggest, this intends to be a replacement for the existing SlackRTM plugin.  Still a work in progress, but I thought I'd raise it now to gather some input/feedback.  It aims to keep things simple, whilst keeping messages first-class citizens on both ends.

Sync data migrations exist for both v2 (`user_data.<team>.synced_conversations`) and the unreleased v3 (`slackrtm.<team>.synced_conversations`) memory keys.  The `slackrtm` config key is morphed into the new format, with a backup of the legacy style written under `"slackrm [legacy backup]"`.

Rough to-do list:
- [x] [sync messages](https://cloud.githubusercontent.com/assets/4025899/24930529/b4f323ee-1f01-11e7-873f-e5c6e55f5c2f.png)
  - [x] HO -> Slack
  - [x] Slack -> HO (without duplicating)
  - ~HO -> Slack -> HO~ (worked all-in-one<sup>3</sup>, or in combination with syncrooms)
  - [x] [action and edit flags](https://cloud.githubusercontent.com/assets/4025899/24928838/c154a9ba-1efb-11e7-8c85-fae16d745362.png)
- [x] sync images<sup>1</sup>
  - [x] [HO -> Slack](https://cloud.githubusercontent.com/assets/4025899/24928771/85d35d6e-1efb-11e7-8a9a-7ad078654e4c.png) (retaining message text if accompanied by image)
  - [x] [Slack -> HO](https://cloud.githubusercontent.com/assets/4025899/24930645/144c0ae0-1f02-11e7-856c-1c1f9dffd541.png)
- [x] join/part syncing
- [x] chatbridge-style config<sup>2</sup>
  - [x] migrate legacy config
- [x] identity links
  - [x] HO -> Slack
  - [x] Slack -> HO
- [x] bot commands
  - [x] confirm identity
    - [x] provide confirmation command when one-way identity confirmed
  - [x] add syncs
  - [x] remove syncs
- [x] execute bot commands using identity
- [x] decent error handling
- [x] make chaining play nice
  - [x] HO -> Slack -> HO
  - [x] Slack -> HO -> Slack

Differences to the existing (v3) SlackRTM:

- maintains its own websocket connection using asyncio, no threading required
- syncs are now stored in config rather than memory
- relay deduping works by storing message IDs in a cache, ignoring them when RTM notifies us
  - means we don't need to tag them with invisible `ho://...` link tags, which have a habit of appearing in plain text clients e.g. IRC/XMPP
- Slack images no longer resent on comment, just when created/shared
- GIFs sent from Hangouts now play in Slack attachments
- Slack-side commands are only processed via direct message to the bot, to avoid polluting channels with multiple command parsers<sup>4</sup>

---

<sup>1</sup> These are shown as attachments within Slack.  Ideally we'd use the files API to upload images into Slack, but having discussed with Slack support, files for bots are rather limited:

- files must be shared into a channel before they are visible to anyone but the bot (this generates an additional message, but the API doesn't give you its ID)
- files can't be shared/mentioned by the bot in a channel unless using `as_user`, which uses the bot's native identity and is mutually exclusive with custom usernames

<sup>2</sup> ~I'm not sure how best to handle the sync config -- looking at how `applicable_configuration` works, both keys and syncs are stored in config.json, but should I be writing that at runtime?~

Other attributes of a conversation / bridge probably belong in memory -- I'm thinking we might need a `bridge_data` section alongside `user_data`, though that's a thought for #821.

<sup>3</sup> ~The standard config structure also allows multiple hangouts, which AIUI means syncs of a HO + HO + Slack form -- should all of this be handled entirely by the plugin?  The control flow would be HO -> Slack -> HO, whereas a better flow would probably be HO <- HO -> Slack...~

<sup>4</sup> I have my bot aliased to the Slack username with a preceding `@`, so that you can effectively mention the Slack-side bot and have the command processed by hangoutsbot.  In v3, this started moaning that the command doesn't exist.

### CODE REVIEW

**Comment by endofline** [comment]
Clarification on questions:
Q2: I assume you mean writing `config.json` at run-time - **yes, you can** - as long as in a sane way. `syncrooms_config` does the same thing. *Un-sane* ways are like the original `telesync` plugin writing its own blank config when it was first loaded, with a broken API key to boot. 
Q3: In an ideal implementation the flow shouldn't matter, since ideally all plugins would be capable of many-to-many bridges. Thus, the directionality, order and plugin config would only affect the sequence of relays. 

If you have new things to suggest to extend the webbridge in a backward-compatible (with v3.0 branch) way, do propose them in a separate pull. Or recommend specific cherry-picks back into v3.0.

**Comment by OllieTerrance** [comment]
2\) I'm fiddling with `bot.config` during migration, though I'll also need to write to it if we want commands to create new / edit existing syncs.  Identities are more of a user data thing, so they're staying in memory.

3\) The `syncs` portion of the config tries to follow the [standard structure](https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/webbridge/__init__.py#L68-L82).  That means the following is currently valid, HO + HO + Slack:

```json
"slackrtm": {
  "teams": {
    "Team": {...}
  },
  "syncs": [
    {
      "hangouts": ["UgXXXXXXXXXXXXXXXXXXXXXXXX", "UgYYYYYYYYYYYYYYYYYYYYYYYY"],
      "slack": [["Team", "CZZZZZZZZ"]]
    }
  ]
}
```

Here, if you say anything in `UgX...`, it gets relayed to Slack, and then back to `UgY...`, effectively a second implementation of syncrooms, but via Slack.

I suppose this isn't really a desired config, the correct setup would be `CZ...` <-> `UgX...` over SlackRTM, then `UgX...` <-> `UgY...` over syncrooms -- it could instead be made to only accept a single hangout in config.json, but turn it into a list when being returned in `applicable_configuration`.

---

The only chatbridge addition so far is 460457a, which looks for `source_action` and `source_edited` fields in the passthru, and formats them nicely in Hangouts -- "(edited)" next to names, and italics for actions.  I suspect telesync can provide values for these fields too, though I've yet to play with Telegram or its APIs.

**Comment by endofline** [comment]
noted, the structure in (3) was intended to be the most flexible to accommodate implementation quirks in various incarnations of each chatbridge plugin at the start of the development - unfortunately, it does imply that various chatbridges can do things they are not capable of. since it is our eventual goal (i hope ;P) that all relay plugins will be configurable from messaging the bot itself, we should intentionally design plugins so actual botmin behaviour is limited to only what each plugin is actually capable of doing, and of course note aforementioned limitations in the documentation. as a rule of the thumb (and also by design of the webbridge/chatbridge), **chat "pairings" for relay plugins should only be between an external and internal (hangouts) chats** i.e. `ho <> slack <> ho`, `slack <> ho <> slack` are fine, but `ho <> ho <> slack` is not

so long as the changes are backward compatible to base 3.0.0, we can incorporate the changes and wait for others to contribute back to the telesync plugin

**Comment by OllieTerrance** [comment]
Wiki page content follows.

---

# SlackRTM Plugin

An alternative to the Slack plugin, which connects to the Real-Time Messaging (RTM) events API.

## Upgrading from the previous SlackRTM plugin

This plugin (`plugins._chatbridge.chatbridge_slackrtm`) replaces an older one with a similar feature set (`plugins.slackrtm`).  Notable changes in the new version:

* chatbridge-aware -- plays nicely with other chatbridge plugins (syncrooms, telesync etc.)
* improved message format -- presents images as Slack attachments, handles action messages
* internal rewrite -- overall reduced bloat in the code, consistency with other bridge plugins

The config format has changed -- on first load of this plugin, any existing config for the legacy SlackRTM plugin will be migrated to the new format.  Syncs are now stored in config rather than memory.

## Config

If you haven't done so already, you'll need to [add a bot user](https://my.slack.com/apps/manage/custom-integrations) to your Slack team and collect its token.

The minimum config required to get started:

```json
{
  "slackrtm": {
    "<team-name>": {
      "token": "<token>",
      "admins": ["<user-id>", ...]
    }
  }
}
```

Add this to your config.json, and include `_chatbridge.chatbridge_slackrtm` in your `plugins` list.  This will start an RTM connection for each named team.

## Commands

### Syncing

You can pair a hangout with a Slack channel, allowing messages and images to be synced in both directions.

* in the hangout to be synced: **slack_sync _team-name_ _channel_**
* in a one-to-one with the Hangouts bot user: **slack_sync _team-name_ _channel_ to _hangout_**
* in a direct message to the Slack bot user: **sync _channel_ to _hangout_**

There is also an analogous **unsync** command, e.g. **slack_unsync _team-name_ _channel_ from _hangout_**.

### Identities

Any user in Slack may link their profile with a Hangouts identity, thus allowing them to run bot commands and trigger mentions from within Slack.

Identities must be confirmed from both Slack and Hangouts.

* in a one-to-one with the Hangouts bot user: **slack_identify as _team-name_ _slack-user_**
* in a direct message to the Slack bot user: **identify as _hangouts-user_**

**Comment by endofline** [comment]
some observed bugs with this implementation:
* **migration issue**
  the original relay configuration for: **slackChannelA <> HO <> slackChannelB** in `memory.json`:

  ```
  "synced_conversations": [
    {
      "channelid": "slackChannelA",
      "hangoutid": "HO",
      ...
    },
    {
      "channelid": "slackChannelB",
      "hangoutid": "HO",
      ...
    }
  ```
  gets migrated to `config.json` as:

  ```
  "slackrtm": {
    "syncs": [
      {
        "channel": [
          "SAME-TEAM",
          "slackChannelA"
        ],
        "hangout": "HO"
      },
      {
        "channel": [
          "SAME-TEAM",
          "slackChannelA"
        ],
        "hangout": "HO"
      },
      {
        "channel": [
          "SAME-TEAM",
          "slackChannelB"
        ],
        "hangout": "HO"
      }
    ],

  note: extra slackChannelA
  ```
*  **relay issue**
   messages in **slackChannelA** aren't relayed via the HO to **slackChannelB** even after `config.json` has been corrected. this is a rather unusual use-case, but its apparently applicable, re: #813

**Comment by OllieTerrance** [comment]
Migration issue is down to importing both v2 and v3 data, where in your case you had both syncs in one place, but one of them duped in the other place.  It'll now take v2 data only if v3 doesn't exist (to avoid importing any stale syncs).

**Comment by endofline** [comment]
im not too familiar with the this branch yet, but on v3 slackrtm, i established a separate bridge instance for each channel-ho pair which only cared about that specific pair. each instantiated bridge has a uid, so simply instantiating multiple copies will create unique norelay flags that are only applicable to that specific instance. thus in v3 slackrtm, slackChannelA <> HO <> slackChannelB is actually treated as:
```
bridge instance 1: slackChannelA <> HO (norelay flag = slackrtm-1)
bridge instance 2: slackChannelB <> HO (norelay flag = slackrtm-2)
```
as far as i know, it should be possible (and desirable) to create "dumb" relays on a per-pair basis with no knowledge of each other to reduce the amount of "magic" we need inside a relay plugin to handle these edge-cases.

**Comment by OllieTerrance** [comment]
The downside with that is (in the naive case) one RTM connection per sync, rather than per team.  For multiple HO<->Slack syncs across distinct hangouts and channels, the overhead grows...

I suppose this needs Slack logic separated from bridge logic, then share RTM connections with all bridge instances working on the same team.

**Comment by pleasantone** [comment]
That's what I did in my aborted & unpublished rewrite.  A slack team simply becomes a shared resource of a number of slack syncs.

**Comment by OllieTerrance** [comment]
Got the per-sync bridges working, Slack->HO->Slack now behaves.  Not committed yet, the commands are still borked until they can figure out which bridge to interact with...

**Comment by OllieTerrance** [comment]
There's no API-friendly way to destroy a bridge if the user wants to unsync a conversation.

I can unlink it from the Slack-side events, but it's still connected to Hangouts, and neighbouring bridges are still aware of it.  Afaict there's no way to undo a `plugins.register_handler(function, type)` either.

**Comment by endofline** [comment]
Yeah, bit of background here:

Handlers were never meant to be registered dynamically, only as part of a plugin `_initialise` and right now would only be [destroyed upon plugin unload](https://github.com/hangoutsbot/hangoutsbot/blob/d6b54691e71ac20759155b06cb79c4c57ba25dc4/hangupsbot/plugins/__init__.py#L466).

Although there isn't a documented way yet to do this in v3, is the above pattern possible useable for your purposes? We could add it to to the bridge instance class, perhaps an idiomatic "close" method that would then tear-down all associated handlers with their bridge instance.

**Comment by OllieTerrance** [comment]
I tried implementing a set of `unregister_handler()` methods, but because we're implicitly promoting non-coroutines to coroutine objects, we have no reference to the original method.  This means we can't match `bridge._repeat()` back to its corresponding pluggable entry.  (`_broadcast()` can be matched because sending events aren't converted.)

I'm not too familiar with the internals here, but I think possible options are:

* Store the original function in the pluggables, and generate a coroutine object at event time.
* Use some form of label/ID at registration time, that can be referenced at unregistration.
* Null bridge implementation: unsyncing a conversation removes it from the config, but prompts the user to reload the plugin in order for it to take effect.

**Comment by endofline** [comment]
latest set of v3.0 framework changes adds (manual) `close()` method to webbridge which deregisters handlers previously registered by the constructor. you can also manually deregister a handler by using `plugins.deregister_handler(<function>, type="<original type>")` where `<function>` is either the original unwrapped function or the actual coroutine, which is now returned when you call `register_handler()` in the first place. i would recommend using the actual coroutine instead of the unwrapped function. dd17d75d11421219b8c148b140c9725d63f8ed8c shows how the v3 slackrtm was converted to support both late-binding + deregistration

**Comment by ckanoab** [comment]
> Identities
> 
> Any user in Slack may link their profile with a Hangouts identity, thus allowing them to run bot commands and trigger mentions from within Slack.
> 
> Identities must be confirmed from both Slack and Hangouts.
> 
> in a one-to-one with the Hangouts bot user: /bot slack_identify as team-name slack-user
> in a direct message to the Slack bot user: identify as hangouts-user

This could be simpler for the user if you adapt the method used in telesync https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/plugins/telesync/__init__.py#L836

**Comment by OllieTerrance** [comment]
Indeed -- it's been suggested a few times, but never made it back to this issue, so I haven't yet remembered to do something about it.  It's on the to-do list now.  🙂

That said, I'm not sure of the benefit of having both steps confirmed from the same side, as you still need to go to the other one to retrieve the code, and we have command processing on both sides anyway...

**Comment by ckanoab** [comment]
You still need to message on both sides with the Telesync method however the user doesn't need to know their user id for either. Generate a unique code in slack which establishes team and user id, then use that code in HO to connect.

**Comment by azack** [comment]
I've been running this for a bit now and support merging it.  Some notes:
1. Seems an overall improvement to the non-chatbridge slackrtm v3.
2. It does not support as many slack-side commands as v3 slackrtm (listsyncs, help, etc)
3. There are still image-sync issues from HO to Slack, but they might not be specific to or related to this PR and more of an issue with Slack itself (needs additional debugging)
4. There are some related PRs that improve upon the functionality, see #867 
5. This was not yet updated to support the newest hangups, so you may need to pin the requirements version: `git+https://github.com/tdryer/hangups.git@v0.4.4`

**Pull request closed without merging**
