### PR TITLE
Plugin/forecast

### PR DESCRIPTION
**Pull request by shoelsch**
### Forecast Plugin

Geolocates a user-supplied address using the Google Maps API and retrieves the current forecast from the Forecast.io API (requires an API key).

#### Bot commands

`/bot forecast <location>` Get location's current weather.
`/bot forecast` Get current weather of last used location.
`/bot forecast unit <unit>` Set unit by which to display degrees

### CODE REVIEW

**Comment by thannemann** [comment]
How is unit stored? Per user, hangout, or bot?

**Comment by shoelsch** [comment]
It's currently stored per hangout. But there's definitely an argument for per user.

I guess my assumption is that a hangout is made up of culturally similar people. So, I chat with users only from the U.S., but if I were to live in China, I would still want my weather to be in degrees F, for the sake of the other users and to conform to the temperature scale that I grew up with.

I should also add that the major use case of this plugin by my group of friends is comparing/contrasting one place's weather to another's, all in one chat window.

Would love to get feedback on this issue, though.

**Comment by pleasantone** [comment]
Merged by hand into staging, would appreciate a code review, @shoelsch.
Thank you for the excellent work!

**Comment by nylonee** [comment]
This looks awesome!
@shoelsch Would you possibly be able to add this to the [wiki](https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-List)? Then I can complete PR #489 =)

**Comment by nylonee** [comment]
Was merged by hand, closing PR

**Comment by shoelsch** [comment]
Added a wiki page [here](https://github.com/hangoutsbot/hangoutsbot/wiki/Forecast-Plugin).

I plan on doing the code review @pleasantone requested this evening (PST).

**Pull request closed without merging**
