### PR TITLE
Adds jpeg support to the image_links plugin

### PR DESCRIPTION
**Pull request by saschalalala**
Nothing more

### CODE REVIEW

**Comment by nylonee** [comment]
HAVE YOU TESTED THIS ON YOUR LOCAL BOT AND ON A DEPLOYED BOT AND CHECKED WITH EVERY DEVELOPER THAT IT'S OKAY WHAT IF IT BREAKS SOMETHING

**Comment by nylonee** [comment]
Kidding xD Thanks for add, I'll merge this now

**Comment by gurumadmat** [comment]
Epic 😄

**Comment by saschalalala** [comment]
Great :D

**Comment by pleasantone** [comment]
Appears to already have been merged?

**Pull request merged**
