### PR TITLE
Added some features to Telesync plugin

### PR DESCRIPTION
**Pull request by jhonnyam123**
- Added sync functionality for replies in telegram. Replies include name and beginning of text from the original message
- Added some keys to telesync config section, to enable/disable added features
- Added bot_name key to config section, so bot name can be stripped from replies to synced messages in Telegram 
- Moved folder for photos to ~/.local/share/hangoutsbot/telesync/telesync_photos/. This should maybe move to telesync config section.
- Added sync for stickers from Telegram. If enabled they will be posted as normal photos in Hangouts. Transparent areas are black, don't know how to change that.
- Removed channel name from synced messages on both sides to improve readebility

### CODE REVIEW

**Comment by nylonee** [comment]
There's some really good stuff in this, I've put forth some spots which could do with improved code, but overall I'm quite pleased with the code.

In the future, it would be less of a daunting task for us to do a code review if you break up the PR such that it only changes one thing at a time, and clean up the commits a little so that we get more useful information rather than 'debugging' on the majority of commits. This also would mean that the plugin's less likely to break, and if it does it's easier to pinpoint where the error is. [Here](http://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests/) are some more good tips for PR's.

**Comment by nylonee** [comment]
Oh. And one more thing, I'd love it if you could add what you changed to the [telesync wiki](https://github.com/hangoutsbot/hangoutsbot/wiki/telesync-Plugin) so that other developers and bot admins know where to get started with your code.

**Comment by jhonnyam123** [comment]
Hi, i'm sorry, this was actually my first PR in my life.
I will update the code and fix some bugs me and others just found out. This PR was more like my actual state and i didn't know how to split this up afterwards.
Thanks for the feadback, i will read the tips you proposed, thanks for that too.

**Comment by jhonnyam123** [comment]
Closing this PR to split it up in to one PR per added feature.

**Pull request closed without merging**
