### PR TITLE
TL;DR plug-in now supports edit command

### PR DESCRIPTION
**Pull request by makiftasova**
I've tried to make tldr's are editable. now they can be edited but timestamp still stays unchanged.

### CODE REVIEW

**Comment by makiftasova** [comment]
Ops, it seems i forgot add sample usage

`/bot tldr edit <"Message">` will do the trick

**Comment by nylonee** [comment]
I've merged this into staging, ready to be merged into master.

Also I've updated the wiki, adding a new [tldr](https://github.com/hangoutsbot/hangoutsbot/wiki/TLDR-Plugin) page

**Comment by ADetectionAlgorithm** [comment]
Any chance we can actually get this merged into main?  It has been added to the wiki, but never actually merged...

(Checked with bot, not part of TLDR plugin)

**Comment by nylonee** [comment]
This has been merged, not sure why it didn't close automatically. Closing this manually.

**Comment by ADetectionAlgorithm** [comment]
@nylonee so this functionality should be implemented in current bot configs?  My bot loaded less than a week ago is not showing this capability or recognizing syntax as shown in the wiki.

**Comment by nylonee** [comment]
I merged the pull request yesterday, make sure to pull again if you haven't
done so in the last couple of hours.

**Pull request closed without merging**
