### PR TITLE
Change prints to logging

### PR DESCRIPTION
**Pull request by pleasantone**
Does what it says. Obviously more plugins to go.

### CODE REVIEW

**Comment by pleasantone** [comment]
Ignore this pull request, I am going to re-submit it with all modules fixed.

**Comment by pleasantone** [comment]
Hrm, I'm not sure how to handle logger inside a class. Please review this merge request, it's not entirely a no-brainer.

**Comment by pleasantone** [comment]
I think this patch needs more testing time, I don't have a good enough jig to test everything. I don't want to break 2.7

**Comment by endofline** [comment]
Oops, ignore the referenced issue (322) - I referenced the wrong request

**Comment by endofline** [comment]
This has been merged into my "bleeding edge" branch (re: #311) that will be merged into staging within the next few hours - I've reverted some changes that conflict with the new aiohttp/asyncio implementation which is documented in the merge comment. Nothing needs to be done with this PR, it will auto-close.

**Pull request merged**
