### PR TITLE
Create send_html_to_user_and_conversation

### PR DESCRIPTION
**Pull request by pleasantone**
Refactor the code in help that sends both public and private data, and warns users if a 1:1 is not available into its own function, so that it can be used by plugins as well.

### CODE REVIEW

**Comment by pleasantone** [comment]
Note: while this works, you'll see the get_1to1 is commented out and I'm using the older method.
For some insane reason, when the code is moved out of the inline in help, the yield version fails to work.

The routine in question appears to not even be called (checked with debugging prints).

**Comment by endofline** [comment]
Probably an `asyncio` gotcha: by moving it into its own function, the parent function may need to be wrapped with an `asyncio.coroutine` decorator. I may have to refactor this into two separate functions, an `asyncio` and a "standard" flavour - the former being preferred. The function names may be tweaked slightly.

**Comment by endofline** [comment]
Compatible changes have been merged to staging in #282 - this PR will close automatically when staging is merged to master in #248

**Comment by pleasantone** [comment]
I don't need the standard version, should you wish to nuke it.

**Comment by endofline** [comment]
alright, as long as nobody uses it - it's a fairly "advanced" function anyway ;)

**Comment by endofline** [comment]
I have removed `send_html_to_user_and_conversation` from staging branch and updated the [wiki](https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-Sending-Messages#send-private-message-to-user-and-optional-public-message-simultaneously)

**Pull request merged**
