### PR TITLE
Silentmode

### PR DESCRIPTION
**Pull request by gurumadmat**
Adding option to make quieter.
Wit option on (globally or per conversation ID)  not will no longer respond to blocked or unknown commands. Also not enough parameters message will not be displayed.

### CODE REVIEW

**Comment by ADetectionAlgorithm** [comment]
Would the option be global or per-conversation?

**Comment by gurumadmat** [comment]
@ADetectionAlgorithm As I said in the pull request above you can define it both ways. 
See adjusted example config file here af7df68046d6b9de0919b3818987cfef78210e7b

**Comment by nylonee** [comment]
Nice! Just a few things I want to ask/clarify:
* If there is nothing in the config (eg. current users of the bot who pull this change) what is the default action?  

```"silent" in bot.tags.useractive(event.user_id.chat_id, event.conv.id_)```
* Can you walk me through why you look for the 'silent' tag?

**Comment by gurumadmat** [comment]
If no config is found the plugin will probably raise an exception. I search for tags so you can use tagset to put a ho in silentmode.

**Comment by thannemann** [comment]
I don't know if it would raise an exception. Because of the if not (...

**Comment by nylonee** [comment]
Could you check that and catch the exception if any? Otherwise current bot users will run into errors at the framework level once they pull this.

Other than that, this looks good to go.

**Comment by gurumadmat** [comment]
No exceptions, when no config directive present, bot responds as usual.
Continuing with merge.

**Pull request merged**
