### PR TITLE
Change last remaining print's to use logging system

### PR DESCRIPTION
**Pull request by pleasantone**
Also, --debug, on the command line, will override the root debugging level on a config-file specified logging configuration.

I'm not sure why you left some things as prints, this commit could use your eyes and thought before merging.

### CODE REVIEW

**Comment by endofline** [comment]
In #345, I've reorganised some files and ported the logging changes. Some differences:
* `print_conversation()` is maintained as print for historical reasons. Also, since it behaves more as an "downstream" function it will be maintained as is
* Elevated event logging to `INFO` (and reduced verbosity) and removed the need to explicitly call `print_debug` or `log_debug` - it is logged on instantiation. This may require modifications to your custom logging dict if you require suppression of the logs

**Comment by endofline** [comment]
Confirmed and verified in #331

**Comment by pleasantone** [comment]
I'm concerned about the change you made to take my changes from logger.debug to logger.info for printing conversation events.  While it may be "backwards compatible", it's actually quite verbose, and it also burns a fair chunk of CPU for every single event we have to process.

It seems to me that folks who want it, have the option to configure DEBUG in their logging config, or use the --debug command argument that's already there, works, and is respected.

How do you feel about changing the level back to debug, and for CPU sanity, wrapping the entire call in "if logger.isEnabledFor(logging.DEBUG)" so we don't have to do all of that formatting and output just to throw it away because log level is not debug at that point?

**Comment by endofline** [comment]
Discussion continued in #349

**Pull request merged**
