### PR TITLE
Restrict debugging messages to running under --debug

### PR DESCRIPTION
**Pull request by pleasantone**
Cut down on some of the debug messages that aren't interesting when we're not debugging.

### CODE REVIEW

**Comment by endofline** [comment]
Presently, I'm revamping the entire logging system, which is kind of haphazard to begin with. Basically, replacing prints with proper logging in core files. May add some extra flags as well and make debugging decent at INFO log level, instead of having to run it in DEBUG - as you can imagine, this is headache-inducing :sweat_smile:

**Comment by pleasantone** [comment]
As long as you're getting to it, feel free to close out this pull if you'd prefer. Awesome work!

**Comment by endofline** [comment]
No worries, I'll leave it up since I can use this for referencing in other pulls/issues at the moment.

**Comment by endofline** [comment]
For your reference, #273 - still work in progress

**Pull request closed without merging**
