### PR TITLE
Added Profile synchronisation to telesync plugin

### PR DESCRIPTION
**Pull request by jhonnyam123**
Allows Hangouts bot to use g+ user name in Hangouts instead of the Telegram user name.
Users can set up sync in private chats with TG and HO bot.

In Telegram use /syncprofile and copy the answered command into pHO with the bot.
To remove sync use /unsyncprofile in Telegram

### CODE REVIEW

**Comment by jhonnyam123** [comment]
Updated Wiki for telesync plugin

**Comment by makiftasova** [comment]
I've made some changes to the wiki page (mostly visual changes and some typo fixes)

**Comment by nylonee** [comment]
@jhonnyam123 It looks like a stray .gitignore update got merged in too, can you confirm that it's safe to disregard the .gitignore file when I pull this into the master branch?

**Comment by jhonnyam123** [comment]
I think that was by accident, i didn't change anything on purpose there. I guess my IDE added some project/profile files.

**Pull request merged**
