### PR TITLE
Remove default "/bot" alias when botalias plugin is loaded

### PR DESCRIPTION
**Pull request by j16sdiz**
Remove "/bot" to prevent bot wars.

### CODE REVIEW

**Comment by endofline** [comment]
this PR may remain open for awhile while we gather feedback. as a workaround, in the meantime, use `/bot botalias remove /bot` to remove the default "/bot" prefix

**Comment by nylonee** [comment]
I like the option of manually removing the `/bot` alias case-by-case, instead of starting a new bot without the alias.

**Comment by nylonee** [comment]
Is this something that people would like to see merged in? If not, I might close this PR since it's been open for almost a year now

**Comment by JosephBlock** [comment]
If it is to be merged, I would add a prompt on first run to set alias like how setting to auth cookie

**Comment by cd334** [comment]
@JosephBlock I think, this is a good idea

**Comment by nylonee** [comment]
The botalias plugin is no longer loaded on first start of the bot. As such I think it'll be confusing for the user if the botalias plugin is loaded and it suddenly stops receiving /bot commands.

**Pull request closed without merging**
