### PR TITLE
Merge Patrick Cernko's SlackRTM plugin

### PR DESCRIPTION
**Pull request by pleasantone**
Patrick has graciously given us permission to incorporate the SlackRTM plugin into the main
bot distribution.

This plugin uses Slack's RTM API, instead of its webhook API to bridge between hangouts and
Slack.  Some of the advantages are:
* we can sync private groups
* images get synced as well
* only one configuration entry per slack team, not per channel
* only one integration required between hangouts and Slack required

Still pending: Wiki documentation of SlackRTM, clean up logging to use python3 constructs where appropriate.

### CODE REVIEW

**Comment by errror** [comment]
About wiki documentation: I'd be happy do do that as well, we did some (german) preliminary work on the documentation already: https://docs.google.com/document/d/1t7Fu0xqeSeN4rBNAQAjFGPtXP0S-gwPhcT5P4Wzijy8/edit

**Comment by nvrrvn** [comment]
This version has trouble syncing images in a HO-Slack-HO scenario. The second HO doesn't get images posted in the first HO. I didn't have the chance for a deeper analysis yet. The last version on https://github.com/errror/hangupsbot works fine in this scenario.

**Comment by pleasantone** [comment]
That's odd, it's the same code

**Comment by nvrrvn** [comment]
Found it, there's a typo in line 472.

logger/info...

**Comment by errror** [comment]
That's what I hate about python: syntax error's that are only detected when the corresponding code part is run. I have code, where some parts are only run once a year (or less) and I always have an ungood feeling about them, because they are also often hard to test.

Anyway, thanks @nvrrvn for finding this issue.

**Comment by pleasantone** [comment]
@errror I took your comment as motivation to make it so we can syntax check the code, and apologies for introducing that syntax error in your code in the first place.

I split this up into 3 separate commits, so that the typo would stand out, but in the third commit, I ended up making two non-mechanical changes I'd appreciate a code review on.

1) I don't think fromDict ever worked! It was in depreciated code, but I fixed it anyway.
```
-    def fromDict(sync_dict):
+    def fromDict(self, sync_dict):
```
and 
2) raw prefixes on two of the regexs were missing (in the second case it's because the +'ed addition wasn't prefixed as raw

```
      def textToHtml(self, text):
-        reffmt = re.compile('<((.)([^|>]*))((\|)([^>]*)|([^>]*))>')
+        reffmt = re.compile(r'<((.)([^|>]*))((\|)([^>]*)|([^>]*))>')

and

     def handleCommands(self, msg):
-        cmdfmt = re.compile(r'^<@'+self.my_uid+'>:?\s+(help|whereami|whoami|whois|admins|hangoutmembers|hangouts|listsyncs|syncto|disconnect|setsyncjoinmsgs|sethotag|setimageupload)', re.IGNORECASE)
+        cmdfmt = re.compile(r'^<@'+self.my_uid+r'>:?\s+(help|whereami|whoami|whois|admins|hangoutmembers|hangouts|listsyncs|syncto|disconnect|setsyncjoinmsgs|sethotag|setimageupload)', re.IGNORECASE)
```

**Comment by pleasantone** [comment]
@errror If you can do the wiki documentation, once it's checked in, we can merge in staging, so thanks for offering if it's still on the table

**Comment by nvrrvn** [comment]
@pleasantone your fromDict change breaks the setup of the RTM connections
```
2015-12-06 01:00:29 ERROR plugins.slackrtm: SlackRTMThread: unhandled exception: fromDict() missing 1 required positional argument: 'sync_dict'
Traceback (most recent call last):
  File "/home/hobot/apps/hangupsbot_v2.7.3/hangupsbot/plugins/slackrtm.py", line 1044, in run
    self._listener = SlackRTM(self._config, self._bot, self._loop, threaded=True)
  File "/home/hobot/apps/hangupsbot_v2.7.3/hangupsbot/plugins/slackrtm.py", line 345, in __init__
    self.syncs.append(SlackRTMSync.fromDict(s))
TypeError: fromDict() missing 1 required positional argument: 'sync_dict'
```

**Comment by errror** [comment]
Tried to create a documentation: https://github.com/hangoutsbot/hangoutsbot/wiki/SlackRTM-Plugin

What do you think. Feel free to enhance or fix it. ;-)

**Comment by pleasantone** [comment]
Done, we're ready to merge.

**Pull request merged**
