### PR TITLE
modified autoreply and humor_hangoutsbot plugins to allow for images to be sent

### PR DESCRIPTION
**Pull request by thannemann**
modified autoreply plugin to allow for images to be sent, this uses code from the image_links plugin for validating an image link before using it, if the validation returns false, then the text is attached as normal.

### CODE REVIEW

**Comment by thannemann** [comment]
Apparently all my commits to my branch are pushing directly to the same pull request. I guess I have more to learn about git.

**Comment by thannemann** [comment]
the last commit was adding an additional config command to allow both global and conversation auto replies to be applicable.  I combine the tulp for both autoreplies and then search the keywords in that combined list.  for backwards compatibility If this new config option is not there it defaults to the current only conversation not global response

**Comment by thannemann** [comment]
in this line, autoreplies_list1 = bot.get_config_suboption('global', 'autoreplies')  I used the word gobal as  an conv.id to fake out the conversation ID, so I coud get the global list

**Comment by endofline** [comment]
the convention `bot.get_config_suboption('global', 'autoreplies')` seems redundant - why not just use `bot.get_config_option('autoreplies')` which will directly check the "global" config for autoreplies, rather than incurring the overhead of scanning a non-existent "global" key then defaulting to the global namespace at https://github.com/hangoutsbot/hangoutsbot/pull/569/commits/cc6de7d8feb0916be9a263cf2574fe7f3fd54c6b#diff-50dcb2155c542bedace2b9032119c078R42

OTOH. if your original intent was to create a shared namespace for combined autoreplies that exists independent of the standard globally-defined autoreplies key (which are overidden by per-conversation autoreplies), then the key should be prefixed with the plugin namespace e.g. `autoreplies.combined`.

The corresponding key `global_autoreplies_enabled` can be more descriptive, e.g. `autoreplies.combine-with-global` (as opposed to the default behaviour of per-conv autoreplies overriding global defaults)

**Comment by thannemann** [comment]
@endofline the intent is to be able to override the current behavior of ignoring global autoreplies when a per conversation auto reply exists. This is why I named the `global_autoreplies_enabled` i was not looking to create a whole new namespace for this.

Yes I agree using `bot.get_config_option('autoreplies')` is better.
.

**Comment by pleasantone** [comment]
I'd prefer to not have so much cut-and-paste from the imagelink plugin.
Can you refactor to call the imagelink plugin's code?

**Comment by thannemann** [comment]
The intent of the plugins are different, yes I reused the other code but
that was because it worked well. I thought about just posting the link and
letting the image link plugin pick it up but for reasons of bot looping it
does not pickup it's own links.

**Comment by pleasantone** [comment]
I have a problem with the same chunk of code existing in 3 separate locations.
I'd advise that you refactor all three plugins and have them import a file in the plugin directory called _validate_links.py that has the link validation routine in it.

**Comment by adam-ludgate** [comment]
:+1:
Fix the duplicate code and merge this, would be good :)

**Comment by nylonee** [comment]
Is there still the intent to work on this PR?

**Comment by PrinterElf** [comment]
I think for autoreply at least, this has already been covered in another PR #731

**Comment by thannemann** [comment]
I don't know enough to write the separate file to parse the images. If I
had figured it out I would have corrected Paul's concerns long ago.

**Comment by thannemann** [comment]
@nylonee @PrinterElf I am working on a new PR that will resolve the issue with this one and also incorporate the additional fixes from pr #731 so I am closing this one and will submit a new one.

**Pull request closed without merging**
