### PR TITLE
Spawn an arbitrary unix command asynchronously

### PR DESCRIPTION
**Pull request by pleasantone**
Spawns an arbitrary command, redirect stdout back to
conversation, stderr to 1:1

See the plugin for the documentation.  If code review finds it acceptable,
I'll merge the documentation into the wiki.

### CODE REVIEW

**Comment by pleasantone** [comment]
@nylonee @endofline I'd appreciate a code review at your convenience, as you know the code I'm messing with better than I do.

**Comment by thannemann** [comment]
What could the purpose of this plugin be? (why would you want to run unix command line commands from the bot) it seems like you are adding a hole right into the bot back-end by adding this as a plugin.

**Comment by pleasantone** [comment]
There are plenty of things that the bot can spawn that don't belong in the bot environment. We've got a load of silly plugins that could be retired or off boarded, as they don't need the actual bot environment.

Read the module docs where I talk about security.

**Comment by thannemann** [comment]
I didnt mean to make it sound like a totally bad thing, I had already read your notes, I was just trying to understand the use for allowing this.

**Comment by endofline** [comment]
+1 on this PR - `fortune` being a good simple example for the kind of integration that this plugin introduces. Of course, there is the one security caveat about botmins running the bot as root, but since this plugin doesn't add anything into the existing base config, it should not present any additional security risk for casual botmins. Nevertheless, botmin beware: As noted in the [code comments](https://github.com/hangoutsbot/hangoutsbot/blob/spawn_plugin/hangupsbot/plugins/spawn.py#L50), be aware that running the bot as root carries security risks.

**Comment by umeshrege** [comment]
I am unable to use this plugin. Not sure if I am missing anything?

**Comment by pleasantone** [comment]
Probably.

**Comment by umeshrege** [comment]
Attached is config.json
Every time i use commands listed, it gives Unknown Command
[config.json.txt](https://github.com/hangoutsbot/hangoutsbot/files/308619/config.json.txt)

**Comment by umeshrege** [comment]
What could be wrong? Am i missing downloading of some package or the config.json shared in prev post is not configured properly. If its about downloading package, where can I find them?

**Comment by pleasantone** [comment]
What do the logs say at startup and when you invoke the command, and how are you invoking the command?

**Comment by pleasantone** [comment]
Are you on staging? Is the plugin getting started?

**Comment by umeshrege** [comment]
Do i need to put this file in plugins dir or commands dir?
Do i also need to mention in the plugins section of config.json?

**Comment by umeshrege** [comment]
This is the error I see when bot initialzes
-----------
ERROR plugins: EXCEPTION during plugin init: plugins.spawn
Traceback (most recent call last):
  File "/var/www/hangups/hangoutsbot-1/hangupsbot/plugins/__init__.py", line 359, in load
    the_function(bot)
  File "/var/www/hangups/hangoutsbot-1/hangupsbot/plugins/spawn.py", line 21, in _initialize
    command.register(_spawn, admin=True, final=True, name=cmd)
TypeError: register() got an unexpected keyword argument 'name'
-----------

**Comment by umeshrege** [comment]
Is there anything I am missing here? Maybe, I am making basic mistakes, need some help urgently.

**Comment by umeshrege** [comment]
I was able to fix the above error. Now it says that spawn plugin is loaded. However, when I give command listed in config.json it says unknown command. Where do I need to look at?

**Comment by umeshrege** [comment]
I see this on the screen when I start the bot
plugins: spawn - no commands

**Comment by umeshrege** [comment]
Any update is appreciated. Looking for some help.

**Pull request merged**
