### PR TITLE
Google Calendar plugin

### PR DESCRIPTION
**Pull request by OllieTerrance**
I've started playing with the idea of a plugin that integrates with Google Calendar (#298).  It's a bit rough around the edges at the moment, but thought it might be a good idea to check in for the hangoutsbot side of things.

Currently it supports listing/adding/updating/removing events, and calendars can be global or per-hangout.  Dependencies are [oauth2client](https://oauth2client.readthedocs.io) and the [Google API Client](https://developers.google.com/api-client-library/python/).  Date formats are all `dd/mm/yyyy` for now, but of course would be nice to make that configurable or more flexible.

Authentication is a bit of a pain -- you need to generate an access token (oauth2client's client_secrets.json) first, so I've set the plugin up to run the OAuth flow if run directly (`python -m plugins.gcal`).  I'm happy to document things on the wiki if this does become an official part of hangoutsbot.  🙂

Some bonus questions:
* Is there a standard/nice way to handle complex command parameters?  Currently I'm disregarding `*args` in favour of `shlex.split(event.text)` to preserve quoting for multi-word parameters...
* How best to separate user and admin sub-commands?  Something that can be done with tags, or should I just have two separate commands?

### CODE REVIEW

**Comment by pleasantone** [comment]
Ever consider making this standalone using the spawn plugin instead?

**Comment by OllieTerrance** [comment]
As in a separate app that hangoutsbot calls out to?  I suppose it's doable, but would mean no easy way to configure it -- afaict the spawn plugin can just pass args verbatim?  So would mean e.g. having to specify a calendar each time...

I suppose a better question is, is there a reason _not_ to do this as a native plugin?

**Comment by pleasantone** [comment]
Everything you need is passed down in environment variables and you'd manage your own config.

Yes, the plugin ecosystem is getting flooded with plugins that can legitimately stand on their own and each plugin drags in more library dependency cruft. If you don't need special access to the bot internals then go standalone.

This is gentle back pressure--consider the fact that as a standalone eases your ability to maintain things as well. The API is well defined and makes it easy to separate and re-use code.

**Comment by OllieTerrance** [comment]
Indeed, the spawn plugin does appear a lot more versatile than first thought, plus it would let plugins double-up as CLI tools as well.  I'll have to have more of a fiddle with it.  👍

**Comment by bafplus** [comment]
I realy like this idea...being no coder i definitly need the readme/wiki ;-)

**Comment by OllieTerrance** [comment]
I'll go ahead and close this PR, will see about converting it to a spawn tool.

I still think it would be nice to do it natively (particularly if there's no intention of using it outside of hangoutsbot), but I agree about the sheer number of plugins, and the dependency hell.  Something like [Prosody's module repository](https://modules.prosody.im) comes into mind, where plugins are handled outside of the rest of the code...

**Pull request closed without merging**
