### PR TITLE
Correct error made in previous commit.

### PR DESCRIPTION
**Pull request by PrinterElf**

### CODE REVIEW

**Comment by PrinterElf** [comment]
Don't commit this yet - still not quite right.
I'll have to check next week.

**Comment by PrinterElf** [comment]
**Summary**
The enumeration for storing the settings in config/memory has changed from the prototype of this script, which wasn't quite understood by me when first using it, hence the correction and subsequent retraction.

The list indexing was an error.

The commit below is a tidy up of the help comments to separate the different sections and make it a little more legible.

**Comment by pleasantone** [comment]
If the plugins/tldr branch has been merged, these need to be rebased against staging. Please do so.

**Comment by pleasantone** [comment]
In that case, please close this, create a new MR against staging, with the changes you need merged into staging, thanks!

**Pull request closed without merging**
