### PR TITLE
Added sync for reply_to_message

### PR DESCRIPTION
**Pull request by jhonnyam123**
Synchronization of replies includes now the first 30 chars of the initial message.
Feature defaults to false if not enabled with `"sync_reply_to":true` in config.json.
Additionally you can set the bot's first name in the config so replies to synced messages use the actual name in the initial message
`"bot_name":"<tg bot pre name>"`

### CODE REVIEW

**Comment by jhonnyam123** [comment]
Update Wiki for telesync plugin

**Comment by makiftasova** [comment]
bot.getMe() should give bot id, bot first name and bot username for telegram side. I don't think we need to keep a field in config for any of them

**Comment by jhonnyam123** [comment]
@makiftasova i'm obviously not too firm with python, especially having some trouble with asyncio. If you can direct me on how to retrieve the actual data from getMe() that would be awesome.

**Comment by makiftasova** [comment]
since getMe() is also a coroutine, you have to call it in asyncio eventloop. 

```python
def _get_bot_data(self):
    loop = asyncio.get_event_loop()
    return loop.run_until_complete(self.getMe())
```

should return a dict something like
```python
{'id':'TELEGRAM_USER_ID', 'first_name':'MyBot', 'username':'MyTelegramBot'}
```

**Comment by makiftasova** [comment]
I've added bot.id, bot.name and bot.username for TelegramBot with pr #666 
you should be able to use them now (unless I've screwed up something with setattr calls)

**Comment by jhonnyam123** [comment]
Thanks for the help @makiftasova i rebased on to staging and updated my feature to use the new variables. Works like a charm.

**Comment by TheSleepySlee** [comment]
Hi, where can I get the latest file for telesync which works?
I am trying to get reply and sync of stickers working, but seems these features are in 2 different py files. thanks.

**Comment by JosephBlock** [comment]
The staging branch I believe, I also have a fix for gifs, but have not made
a patch

**Comment by TheSleepySlee** [comment]
At least this patch 657 is not merged, so reply should not work on staging. Or?

**Comment by nylonee** [comment]
I'd much rather this used `memory` instead of the `config` to set up replies, so that it can be set per conversation. That being said, it looks like most of the functionality in this plugin is using config instead of memory, so I'll leave it as is, but a nice rewrite in the future could be to turn the telesync features into memory-based conversation specific toggles.

Will review and pull this into staging shortly

**Pull request merged**
