### PR TITLE
Lastcommand

### PR DESCRIPTION
**Pull request by gurumadmat**
Been using this branch now for some time and seems stable and comes in very handy.
Before merging I'm looking for suggestions -to improve.

Use '/bot c' to show and issue your last command on a global level.

### CODE REVIEW

**Comment by zimler** [comment]
what if you could store some "favorite" commands?
/bot c is as you describe
/bot c1 could be favorite 1
/bot c2 could be favorite 2
etc...

**Comment by gurumadmat** [comment]
Nice idea, but this would clutter up the code. 
Also with the current implementation there is no way of providing different arguments, so this would have no real use.

**Comment by nylonee** [comment]
This is a great idea!
However, I'm a bit nervous about changing the core bot functionality while this code can be done entirely on a plugin level. Is there any chance that that could be refactored?

**Comment by nylonee** [comment]
I'm still a bit iffy about this PR. Documentation and proper commenting is needed, there's a lot of redundancy, and the code needs a refactor to be more pythonic.

**Comment by nylonee** [comment]
I'm going to close this PR for the time being, let's re-open this after merging v3 in, which gives us a new core framework to design the plugin around.

**Pull request closed without merging**
