### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JosephBlock**
Note about the depreciation of the hangout API

### CODE REVIEW

**Comment by pleasantone** [comment]
Joe, this needs to be done against staging, not master.

**Comment by nylonee** [comment]
Has this been a pressing question in recent days, such that we need to add it to the README file?

I'm guessing once we push the latest staging to master, the updated code will speak for itself that the project is indeed still alive and well

**Comment by JosephBlock** [comment]
Can be added to the Wiki instead. There are still people who think hangouts is going away..

**Comment by nylonee** [comment]
I've updated the wiki. If there are still concerns that should be addressed in the upcoming weeks, I'll add this to the README.

**Pull request closed without merging**
