### PR TITLE
hangupsbot.service restart after crashed

### PR DESCRIPTION
**Pull request by jumoog**

### CODE REVIEW

**Comment by jumoog** [comment]
#624 #623

**Comment by pleasantone** [comment]
Negative. You're now running as root. please repair that change.

**Comment by jumoog** [comment]
Restart of 3 seconds was the best value .. i tried 1,2 too

**Comment by pleasantone** [comment]
Also execrestart vs execstart and you didn't cover 623? Was this tested?

**Comment by pleasantone** [comment]
So in 623, he points out we could use a Wants. On Debian its true there are likely other items also wanting it (e.g. Sshd), so we don't see that bug, but he's technically correct and it should be added and tested.

What concerns me more is you renamed execstart to something that doesn't exist.

Also, thinking more about it, I had set restart to on failure for a reason. If you want to kill the bot on purpose, remotely, for debugging, you can ! quit. This removes that.

**Comment by jumoog** [comment]
i had some cases where the bot crashed and doesn't restart. 

keep running is more important for me. You can always stop it via `service stop`

**Comment by bafplus** [comment]
I use this from the start (without the 3 sec delay and execrestart) and works like a charm.
Restarts after crash but also restarts on /bot quit.
Nice and easy way to fully reload/restart bot.

**Comment by pleasantone** [comment]
Declined to accept, it's an example file, if you want to differ from the example, feel free, but forced restart on quit is a user decision.

**Pull request closed without merging**
