### PR TITLE
Matrixsync (WIP)

### PR DESCRIPTION
**Pull request by MTRNord**
This will add an sync plugin for Matrix Server.
Currently it does basic ho<->mx sync and is mostly based on telesync.

Some TODOS are:
 - [x] Fix that from ho synced messages get back synced to ho. (message from ho goes to mx and gets back again)
 - [ ] Add other types of message (example: location (needs google maps api propably as I need coordinates and a name))
 - [ ] Maybe add command support (propablly not working for now)
 - [ ] Add End-to-End encryption support on matrix site. (Means bot can send and recive encrypted messages and can decrypt them for HO) http://matrix.org/speculator/spec/drafts%2Fe2e/client_server/unstable.html#end-to-end-encryption
 - [ ] fix weird 3 times messages in v3 branch
 - [ ] Add Wiki page if plugin is ready

### CODE REVIEW

**Comment by nylonee** [comment]
Sorry for the late response, I'd love an update on your progress in getting this PR completed.

Yes, if you have pip dependencies, it should go in requirements.txt.

**Comment by MTRNord** [comment]
Update will come :) But I currently have lots of exams so it will take some time for an update.

**Comment by nylonee** [comment]
I know the feels. Looking forward to seeing this plugin completed, it looks great so far

**Comment by MTRNord** [comment]
Question: (if anyone read this) does the sync need a video or audio sync? or just image, text and location?

**Comment by MTRNord** [comment]
Also is it possible to force a "typing event"? or is that a V3 feature?

**Comment by MTRNord** [comment]
Ok there seems to be some unknown changes on the matrix api site that do very very bad things (it always returns every mesagge a lot of times) so I need to investigate that

**Comment by MTRNord** [comment]
It seems like matrix has on their side some huge communication problems between servers that cause multiple event triggering. :( This PR has to wait until I have contact to one of the server admins where I got a channel and maybe to some matrix devs. Until that is fixed I will add some missing features and remove the hangups requirement for the event

**Comment by nylonee** [comment]
I will close this PR until it's ready to be resubmitted as a plugin

**Pull request closed without merging**
