### PR TITLE
user and conversation tagging

### PR DESCRIPTION
**Pull request by endofline**
note: WIP, subject to change, discuss further in #121

framework:
* ~~add~~ `chat_id:` filter to `bot.conversations.get()` ~~- useful for finding which conversation 
  a specific user is in, and for determining whether the `chat_id` exists (dd02702)~~  added
  via merge #276 
* tagging functionality (see preliminary docs below)

developer functions: 
* `bot.tags.add(<"user"|"conv">, "<id>", "<tag>")`
  * returns `True` on successful removal, `False` if nothing is written to storage
  * setting a **per-conversation-user-override**: `<id>` must be a string of the 
     following format: `convid|userid` e.g. `bot.tags.add("user", "XYZ|123", "testtag")`
* `bot.tags.remove(<"user"|"conv">, "<id>", "<tag>")`
  * `<id>` and `<tag>` must match an existing entry to remove
  * returns `True` on successful removal, `False` if nothing is written to storage
  * removing a **per-conversation-user-override**: `<id>` must be a string of the 
     following format: `convid|userid` e.g. `bot.tags.remove("user", "XYZ|123", "testtag")`
* `bot.tags.purge(type, id)` ([wiki](https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-User-and-Conversation-Tagging))
* `bot.tags.useractive("<user id>", ["<conv id>"])`
   * return list of active tags for specified `<user id>`, or empty list
   * supplying `<conv id>` takes advantage of any **per-conversation-user-override** set
     for the `<user id>` and `<conv id>` and is **highly-recommended**
     * if no `<conv id>` is supplied, only the user's global tags (if any) will be returned
* `bot.tags.userlist("<conv id>", [[tags]])`
   * returns dict of participating users to tag list (`<chat id>` to `[tags]`), or empty dict
   * supply optional list of tags to filter the list  - if tag list supplied, user must have all specified tags

developer variables: 
* `bot.tags.indices["user-tags"]`
* `bot.tags.indices["tag-users"]`
* `bot.tags.indices["conv-tags"]`
* `bot.tags.indices["tag-convs"]`

Note: `bot.tag.indices` is an in-memory index for fast lookup of user/conv list by tag value, 
  and vice-versa. It is loaded during bot start, and updated each time an `.add` or `.remove`
  is successful. The actual tags are stored by-user and by-conversation in `memory.json` 
  keys:  `user_data`,  `conv_data`

unittest plugin: 
* `tagset <"conv"|"user"> <id> <tag>`
* `tagdel <"conv"|"user"> <id> <tag>`
* `tagindexdump`
* `tagspurge <type> <id>`
* `tagsuser <user id> [<conv id>]`
* `tagsuserlist <conv id> [<tag> [<tag>] ...]`

Assumptions:
* ~~`user id` and `conv id` will never overlap~~ (no longer useful with explicit `type`: `user`/`conv`)
* pipe char `|` won't be used in `user id` or `chat id`
* 3 types of tagging: **per-user**, **per-conversation** and **per-conversation-user-override**
  * **per-conversation-user-override** will always overwrite any other tags set **per-user**
  * **per-conversation** tagging is **not** related to **per-user** or **per-conversation-user-override**

Shortcomings:
* ~~unreliable user data retrieval (hangups-related)~~ ~~resolved by dd02702, force a check
  for existence of user's `chat_id` in at least one conversation's user list~~ permamem 
  allows an exact check for user existence (#276)
* ~~explicit type in tag check vs implicit type for tag add and remove (which one better?)~~
* ~~doesn't solve [per-conversation **and** per-user tags]
  (https://github.com/hangoutsbot/hangoutsbot/issues/121#issuecomment-119632269)~~ 
  implement **per-conversation-user-override**s

TODOs:
* [X] explicit ~~or implicit~~ user/conv type ~~check?~~
* [X] **restrictedadd**: support for **botkeeper** tag (f24f1b4, [wiki](https://github.com/hangoutsbot/hangoutsbot/wiki/Restricted-Add-Plugin#tag-support))
* [X] **monitoradds** support for **mod**, **botkeeper** tag (3821608, [wiki](https://github.com/hangoutsbot/hangoutsbot/wiki/Monitoradds-Plugin))
* [X] **autoreplies** support for **autoreplies-enable**, **autoreplies-disable** tag (9a07cd0, 518d15e
, [wiki](https://github.com/hangoutsbot/hangoutsbot/wiki/Autoreply-Plugin#tag-support))
* [X] figure out how to do _per-conversation **and** per-user tags_
* [X] implement **per-conversation-user-override**
* [X] refactor now that #268 + #276 (permamem) have been merged
* [x] documentation
  * [X] [list by tags](https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-Tags-List) 
  * [x] [developer documentation for tagging](https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-User-and-Conversation-Tagging)
* ~~better commands for tag management~~ (deferred until merged to staging)

### CODE REVIEW

**Comment by endofline** [comment]
Wiki updated:
* https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-Tags-List
* https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-User-and-Conversation-Tagging
* https://github.com/hangoutsbot/hangoutsbot/wiki/Autoreply-Plugin
* https://github.com/hangoutsbot/hangoutsbot/wiki/Restricted-Add-Plugin
* https://github.com/hangoutsbot/hangoutsbot/wiki/Monitoradds-Plugin

**Comment by endofline** [comment]
All changes from this branch accounted for and added to #248 body

**Comment by pleasantone** [comment]
So now that this has been merged, I'm scratching my head about the appropriateness of using it for command permissions... or perhaps we need to extend it a little bit more and/or make the command
parser potentially aware of it?

Old regime:
"foobar" is either registered as a user or admin command

I can override foobar and make it a user command by enumerating all permitted user commands in a
particular conversation id (in config), but that's really the only generic access method I have for controlling access to the command.  If a user gets added to the conversation by anyone, boom, they get the command.

New regime:

I make foobar a user command globally, but then add a test to check check to see if a user has the foobarmaster tag in the conversation that they're attempting to execute foobar in.

    if not "foobarmaster" in bot.tags.useractive(user, cov)
       send back command restricted response

should do the job.

The enhancement I'm mulling about is applying tagging to both the command parser and help, so that we have a generic wrapper to check for permissions and not display commands that users are/aren't allowed to operate.

Thoughts?

btw. beautiful work on the framework

**Comment by pleasantone** [comment]
bot.register_privileged_command("foobar", "foobarkeeper")

would allow only admins and people/conversations tagged with foobarkeeper to execute the command?

that then begs the question, what about subcommands? I don't know of a nice generic way to handle the next part, which would be "foobar read" is allowed but "foobar save" is not unless you have the foobarsavekeeper tag.

Also, there's the question of "do we really want this information stored in permamem or config?"  Permamem is vaguely disposable, and config is less so. I know which file I'd try to save in a fire.

**Comment by endofline** [comment]
@pleasantone That is indeed the next stage of implementation, now that tagging is available - a _sorta-kinda_ privilege escalation model where users with specific tags will have their privileges temporarily raised to run specific admin-level commands when they need to. I'm hoping that such a system would be as transparent as possible.

I haven't thought on the implementation of multiple tags for command running and will look into this. Fortunately, the basic mechanism exist right now in `bot.tags.userlist`.

My two-cents on the memory vs config bit - it's more likely to be in `config.json` - previous input from users suggest that they will more likely configure their command list right inside config.json by hand. 

As for actual implementation, I will branch off shortly after releasing 2.6 (#248) so that we can start on command tagging work - that would be within 24-36 hours from time of this post.

**Comment by endofline** [comment]
@pleasantone - fyi, alpha code in #293 implements the proposed **tagged commands** system

**Comment by pleasantone** [comment]
Ideally, a base level UI convention would support privilege escalation across command groups and subcommands.

As an example, role that we currently tag as “bookkeeper” and “patrons" might be testable against

in book.py:

/bot book
/bot bookreaders

and libraries.py:

/bot libraries

which could be done with something like

    register_tagged_commands({{ [“bookkeeper”, “patrons”] : [ “book”, “bookreaders” ]},

and

    register_tagged_commands({{ [“bookkeeper”, “patrons”] : [ “book”, “bookreaders” ]},


and additionally, it shouldn’t preclude restricting the

/book burn-it-all-down

sub-command to be restricted to users tagged with “head-librarians.”  I’m not suggesting that you write the UI to support subcommands, as that’s turning it on its head, just that the existing test API that you have is great and the UI shouldn’t preclude authorizing subcommands.

**Comment by pleasantone** [comment]
My mistake — I was talking API and you were asking UI.  First off, I’m against system commands.

/bot role <add | delete> <rolename> [ user | conversation | conversation:user ]
— [creates and/or adds] or [deletes] to/from <role>  user, all-in-conversation  or user in conversation

/bot role clear <rolename>
— clear all entries in role and delete it

**Pull request merged**
