### PR TITLE
plugins/showme

### PR DESCRIPTION
**Pull request by DanielCasner**
A simple plugin to retrieve images accessible to the hangoutsbot server but not necessarily to the client.

Documentation is included in the plugin's README.md

### CODE REVIEW

**Comment by pleasantone** [comment]
Daniel, just some tiny feedback...

the bot already has a help function, it would be best if you use that...
`/bot help function` returns the docstring of the function, that's where we put syntax instructions & help

`/bot function` <with no arguments>, in your case, is the place to return possible showme arguments

Arthur and Nihal seem to be eliminating a lot of the more dynamic configuration by moving it to memory.json. Consider the case of allowing bot administrators to be able to add/delete objects, similar to what the tldr plugin does, using memory.json.

YMMV, but I thought I'd give you some feedback, take it for what it's worth.

**Comment by DanielCasner** [comment]
@pleasantone Thanks very much for the feedback. I was unaware of the help for function feature so I will refactor to use that.

I'll look at the dynamic configuration in memory option.

**Comment by nylonee** [comment]
Nice work though! Looking forward to the refactor =)

**Comment by DanielCasner** [comment]
I've moved "help" into the standard place but am leaving configuration in config.json for the time being since sources I anticipate sources will be relatively static in most use cases. If there's interest in the future, dynamic configuration should be straight forward enough for anyone to add given the number of examples available in plugins.

**Comment by kelt8** [comment]
@DanielCasner great work Daniel! Thanks! Was wondering if there's any way to incorporate an accompanying text along with the picture?

**Comment by DanielCasner** [comment]
@kelt8 The plugin references a URL to an image file directly so I'm not sure where any text would be coming from. Do you mean something like posting the time the image was retrieved?

**Comment by kelt8** [comment]
I meant urm, post the picture then on the second line post a description...

**Comment by DanielCasner** [comment]
That much was clear. Where does the plug-in get the text for the
description from?

**Comment by kelt8** [comment]
I was thinking manual like the image sources.

**Pull request merged**
