### PR TITLE
Issue #719 in PR form...

### PR DESCRIPTION
**Pull request by jkg**

### CODE REVIEW

**Comment by jkg** [comment]
Thanks to @PrinterElf for feedback about not including at-all in bot responses - see additional commit at https://github.com/jkg/hangoutsbot/commit/03d65a9e19d1fd605e7d797f75132748424fbcfb

**Comment by JosephBlock** [comment]
@jkg please request the PR into staging

**Comment by pleasantone** [comment]
@jkg this needs to be created against the staging branch, not the master branch

**Comment by pleasantone** [comment]
@jkg https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

**Comment by jumoog** [comment]
#734

**Comment by jumoog** [comment]
can be closed

**Pull request closed without merging**
