### PR TITLE
Add automatic message to chat when bot is added. 

### PR DESCRIPTION
**Pull request by JosephBlock**
Can be used to share info about the bot and how to use it. Disabled by default.

/bot join_message <message> to set message
/bot join_message_enabled <true|false> to turn on or off

### CODE REVIEW

**Comment by pleasantone** [comment]
Doesn't this duplicate the functionality of the more recent autoreply code that has welcome support?

```
 "Ugzmp1WmtFhhKpT5uZV4AaABAQ": {
      "autoreplies": [
        [
          "JOIN",
          "GUEST_ONE_TO_ONE:You joined <b>{conv_title}</b> by invitation of {event.user.full_name}.<br/>line 2'"
        ],
        [
          "LEAVE",
          "GUEST_ONE_TO_ONE:Sorry to see you go, {guest.full_name}. Remember the first rule of .....<br/>"
        ]
      ],
      "autoreplies_enabled": true
    }
```

**Comment by PrinterElf** [comment]
@pleasantone While personally I'm not sure I can see the need for the functionality (surely whomever the offender is can just explain /bot help), I think this is intended to fire if the bot is added to a hangout rather than if a user is added to a hangout the bot is in.

**Comment by pleasantone** [comment]
My mistake, fair enough, thanks for the correction

**Comment by PrinterElf** [comment]
Although I have just realised that I'm not sure how well this would play with restrictedadds.
There may need to be some sort of check/delay to account for the fact that the bot may not be allowed to be there.

**Comment by endofline** [comment]
In the interest of time and focus, I will defer any review, testing and merge of this PR until after a v3 migration. Feel free to add to it though, or publish more comprehensive documentation as markup inside the pr body.

**Pull request closed without merging**
