### PR TITLE
Add Notice

### PR DESCRIPTION
**Pull request by JosephBlock**
When bot is added to a chat, it will send the message set in config to
the chat. Change add_notice_message to the message you wish to be sent, which can be HTML formatted.

### CODE REVIEW

**Comment by pleasantone** [comment]
One universal note for anywhere the bot joins?  How do you see it being used?

"Hi, I'm foobot, type /foobot help to learn more about me?"

**Comment by JosephBlock** [comment]
When the bot is added to a hangout, it will send the string

**Comment by JosephBlock** [comment]
I'm using it to introduce the features the bot provides and help info

**Comment by pleasantone** [comment]
Sounds reasonable to me.. you going to merge it into staging (not master!)?

**Comment by nylonee** [comment]
I will have a play around with this, it looks good, it might even be better to merge it into the default.py plugin if we make the config optional. Thoughts?

**Comment by pleasantone** [comment]
Default.py sounds good to me

**Comment by JosephBlock** [comment]
Probably can change it to use memory.json to store enabled/disabled and allow admins to change the string without restart

**Comment by cd334** [comment]
When do plan to merge this?

**Comment by nylonee** [comment]
I'll have to do some changes to the code and implement it into default.py first. Hopefully within 24 hours it'll be merged into the staging branch for testing.

**Comment by JosephBlock** [comment]
Combined with default.py in #506

**Pull request closed without merging**
